import axios, { AxiosError, InternalAxiosRequestConfig, AxiosResponse } from 'axios';

// 1. Define the shape of your backend's standard error response
interface ApiErrorResponse {
    status: string;
    message: string;
}

//2. Create the custom Axios Instance
export const api = axios.create({
    // Point this to your Express server's base URL
    baseURL: ['http://165.232.160.22:5000/api', 'http://localhost:8086'],

    // CRITICAL: This tells the browser to automatically include the 
    // HttpOnly JWT cookie in every single request!
    withCredentials: true,

    headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
    },
});
// export const api = axios.create({
//     // Hardcoded for local development
//     baseURL: 'http://localhost:8086/api',

//     // CRITICAL: This tells the browser to automatically include the 
//     // HttpOnly JWT cookie in every single request!
//     withCredentials: true,

//     headers: {
//         'Content-Type': 'application/json',
//         Accept: 'application/json',
//     },
// });

// 3. Request Interceptor
api.interceptors.request.use(
    (config: InternalAxiosRequestConfig) => {
        // You can add logic here if needed before requests are sent out.
        // (We do NOT need to attach tokens here because HttpOnly cookies handle it automatically).
        return config;
    },
    (error: AxiosError) => Promise.reject(error)
);

// 4. Response Interceptor
api.interceptors.response.use(
    (response: AxiosResponse) => {
        // ARCHITECTURAL SHORTCUT: 
        // Your Express backend wraps everything in { status: 'success', data: { ... } }
        // By returning `response.data` here, your React components don't have to constantly type `res.data.data`!
        return response.data;
    },
    async (error: AxiosError<ApiErrorResponse>) => {
        // Global 401 Unauthorized Handler
        if (error.response?.status === 401) {
            console.warn('Session expired or unauthorized. Dispatching event...');

            // We dispatch a browser event instead of using `window.location.href`
            // so that our React state (Zustand) can listen for this and cleanly log the user out.
            window.dispatchEvent(new CustomEvent('auth:unauthorized'));
        }

        // Reject with the specific error message generated by your Express AppError class
        const errorMessage = error.response?.data?.message || 'An unexpected error occurred';
        return Promise.reject(new Error(errorMessage));
    }
);